### ISSUE TITLE
Could you please tell the location in the code of CALINET? 

### ISSUE THREAD

**Issue by FairyFali** [dqxiu/CaliNet#2]
I am wondering how you implement the CALINET module. After scanning your code, I can not find it, so could you please specify where in the code the CALINET addition you proposed has been implemented? 

Thanks.

**Comment by dqxiu** [comment]
Hi! Please refer to the kb_layer for the CaliNet module :)
https://github.com/dqxiu/CaliNet/blob/8c9cfd5889d98b4afb7c74f21977acd4b1976fcf/src/modeling_t5.py#L1002
